


from collections import defaultdict



application_rate_units = defaultdict(lambda : defaultdict(lambda : defaultdict(dict)))
daily_usage = defaultdict(lambda : defaultdict(lambda : defaultdict(dict)))
daily_usage_units = defaultdict(lambda : defaultdict(lambda : defaultdict(dict)))
scenario_comments = defaultdict(lambda : defaultdict(lambda : defaultdict(dict)))
unit_exposure = defaultdict(lambda : defaultdict(lambda : defaultdict(lambda : defaultdict(dict)))) #mg/lb ai



scenario_comments['Dust/Powder']['Indoor Environment']['Plunger Duster']['Broadcast; Perimeter/Spot/ Bedbug (course application)'] = ''
scenario_comments['Dust/Powder']['Gardens / Trees']['Plunger Duster'][''] = ''
scenario_comments['Dust/Powder']['Indoor Environment']['Bulb duster']['Perimeter/Spot/Bedbug; Crack and Crevice'] = 'Surrogate data:  plunger duster'
scenario_comments['Dust/Powder']['Gardens / Trees']['Bulb duster'][''] = 'Surrogate data:  plunger duster'
scenario_comments['Dust/Powder']['Indoor Environment']['Electric/power duster']['Broadcast; Perimeter/Spot/ Bedbug (course application)'] = 'Surrogate data:  shaker can'
scenario_comments['Dust/Powder']['Gardens / Trees']['Electric/power duster'][''] = 'Surrogate data:  shaker can'
scenario_comments['Dust/Powder']['Indoor Environment']['Hand crank duster']['Broadcast; Perimeter/Spot/ Bedbug (course application)'] = 'Surrogate data:  shaker can'
scenario_comments['Dust/Powder']['Gardens / Trees']['Hand crank duster'][''] = 'Surrogate data:  shaker can'
scenario_comments['Dust/Powder']['Indoor Environment']['Shaker can']['Broadcast'] = ''
scenario_comments['Dust/Powder']['Indoor Environment']['Shaker can']['Broadcast; Perimeter/Spot/ Bedbug (course application)'] = ''
scenario_comments['Dust/Powder']['Gardens / Trees']['Shaker can']['can'] = ''
scenario_comments['Dust/Powder']['Gardens / Trees']['Shaker can']['ft2'] = ''
scenario_comments['Liquid concentrate']['Indoor Environment']['Manually-pressurized handwand (w/ or w/o pin stream nozzle)']['Broadcast, Perimeter/Spot/ Bedbug (course application); Perimeter /Spot/ Bedbug (pinstream application); Crack and Crevice'] = 'Surrogate data:  wettable powders with manually-pressurized handwand'
scenario_comments['Liquid concentrate']['Gardens / Trees']['Manually-pressurized handwand']['ft2'] = ''
scenario_comments['Liquid concentrate']['Gardens / Trees']['Manually-pressurized handwand']['gallons'] = ''
scenario_comments['Liquid concentrate']['Gardens / Trees']['Hose-end Sprayer']['ft2'] = ''
scenario_comments['Liquid concentrate']['Gardens / Trees']['Hose-end Sprayer']['gallons'] = ''
scenario_comments['Liquid concentrate']['Lawns / Turf']['Hose-end Sprayer'][''] = ''
scenario_comments['Liquid concentrate']['Lawns / Turf']['Manually-pressurized handwand'][''] = ''
scenario_comments['Liquid concentrate']['Gardens / Trees']['Backpack']['ft2'] = ''
scenario_comments['Liquid concentrate']['Gardens / Trees']['Backpack']['gallons'] = ''
scenario_comments['Liquid concentrate']['Gardens / Trees']['Sprinkler can']['ft2'] = 'Surrogate data:  liquid concentrate with hose-end sprayer'
scenario_comments['Liquid concentrate']['Gardens / Trees']['Sprinkler can']['gallons'] = 'Surrogate data:  liquid concentrate with hose-end sprayer'
scenario_comments['Liquid concentrate']['Lawns / Turf']['Sprinkler can'][''] = 'Surrogate data:  liquid concentrate with hose-end sprayer'
scenario_comments['Ready-to-use']['Indoor Environment']['Aerosol can']['Broadcast Surface Spray'] = ''
scenario_comments['Ready-to-use']['Indoor Environment']['Aerosol can']['Perimeter/ Spot/ Bedbug (course application)'] = ''
scenario_comments['Ready-to-use']['Indoor Environment']['Aerosol can with pin stream nozzle']['Perimeter/ Spot/ Bedbug (pin stream application); Crack and Crevice'] = ''
scenario_comments['Ready-to-use']['Indoor Environment']['Aerosol can']['Space spray'] = ''

scenario_comments['Ready-to-use']['Insect Repellent']['Aerosol can'][''] = ''
scenario_comments['Ready-to-use']['Insect Repellent']['Trigger-spray bottle'][''] = ''

scenario_comments['Ready-to-use']['Gardens / Trees']['Aerosol can'][''] = ''
scenario_comments['Ready-to-use']['Lawns / Turf']['Aerosol can'][''] = ''
scenario_comments['Ready-to-use']['Indoor Environment']['Trigger-spray bottle']['Broadcast'] = ''
scenario_comments['Ready-to-use']['Indoor Environment']['Trigger-spray bottle']['Perimeter/ Spot/ Bedbug (course application)'] = ''

scenario_comments['Ready-to-use']['Gardens / Trees']['Trigger-spray bottle'][''] = ''
scenario_comments['Ready-to-use']['Lawns / Turf']['Trigger-spray bottle'][''] = ''
scenario_comments['Ready-to-use']['Indoor Environment']['Gels']['No exposure data available for this application scenario; however, exposure is considered negligible.'] = ''
scenario_comments['Ready-to-use']['Indoor Environment']['Pastes']['No exposure data available for this application scenario; however, exposure is considered negligible.'] = ''
scenario_comments['Ready-to-use']['Indoor Environment']['Foams']['No exposure data available for this application scenario; however, exposure is considered negligible.'] = ''
scenario_comments['Ready-to-use']['Indoor Environment']['Bait (granular, hand dispersal)'][''] = ''
scenario_comments['Ready-to-use']['Indoor Environment']['Bait station / trap (enclosed in child resistant packaging)']['No exposure data available for this application scenario; however, exposure is considered negligible.'] = ''
scenario_comments['Ready-to-use']['Indoor Environment']['Pest strip']['No exposure data available for this application scenario; however, exposure is considered negligible.'] = ''
scenario_comments['Ready-to-use']['Gardens / Trees']['Hose-end Sprayer']['ft2'] = ''
scenario_comments['Ready-to-use']['Gardens / Trees']['Hose-end Sprayer']['gallons'] = ''
scenario_comments['Ready-to-use']['Lawns / Turf']['Hose-end Sprayer'][''] = ''
scenario_comments['Wettable powders']['Indoor Environment']['Manually-pressurized handwand (w/ or w/o pin stream nozzle)']['Broadcast, Perimeter/Spot/ Bedbug (course application); Perimeter /Spot/ Bedbug (pinstream application); Crack and Crevice'] = ''
scenario_comments['Liquid concentrate']['Lawns / Turf']['Backpack'][''] = ''
scenario_comments['Wettable powders']['Gardens / Trees']['Manually-pressurized handwand']['gallons'] = ''
scenario_comments['Wettable powders']['Gardens / Trees']['Manually-pressurized handwand']['ft2'] = ''
scenario_comments['Wettable powders']['Gardens / Trees']['Hose-end Sprayer']['ft2'] = 'Surrogate data:  liquid concentrate with hose-end sprayer'
scenario_comments['Wettable powders']['Gardens / Trees']['Hose-end Sprayer']['gallons'] = 'Surrogate data:  liquid concentrate with hose-end sprayer'
scenario_comments['Wettable powders']['Lawns / Turf']['Hose-end Sprayer'][''] = 'Surrogate data:  liquid concentrate with hose-end sprayer'
scenario_comments['Wettable powders']['Lawns / Turf']['Manually-pressurized handwand'][''] = ''
scenario_comments['Wettable powders']['Gardens / Trees']['Backpack']['ft2'] = 'Surrogate data:  wettable powders with manually-pressurized handwand'
scenario_comments['Wettable powders']['Gardens / Trees']['Backpack']['gallons'] = 'Surrogate data:  wettable powders with manually-pressurized handwand'
scenario_comments['Wettable powders']['Gardens / Trees']['Sprinkler can']['ft2'] = 'Surrogate data:  liquid concentrate with hose-end sprayer'
scenario_comments['Wettable powders']['Gardens / Trees']['Sprinkler can']['gallons'] = 'Surrogate data:  liquid concentrate with hose-end sprayer'
scenario_comments['Wettable powders']['Lawns / Turf']['Sprinkler can'][''] = 'Surrogate data:  liquid concentrate with hose-end sprayer'
scenario_comments['Wettable powders in water-soluble packaging']['Indoor Environment']['Manually-pressurized handwand (w/ or w/o pin stream nozzle)']['Broadcast, Perimeter/Spot/ Bedbug (course application); Perimeter /Spot/ Bedbug (pinstream application); Crack and Crevice'] = 'Surrogate data:  wettable powders with manually-pressurized handwand'
scenario_comments['Wettable powders']['Lawns / Turf']['Backpack'][''] = 'Surrogate data:  wettable powders with manually-pressurized handwand'
scenario_comments['Wettable powders in water-soluble packaging']['Gardens / Trees']['Manually-pressurized handwand']['ft2'] = 'Surrogate data:  liquid concentrates with manually-pressurized handwand'
scenario_comments['Wettable powders in water-soluble packaging']['Gardens / Trees']['Manually-pressurized handwand']['gallons'] = 'Surrogate data:  liquid concentrates with manually-pressurized handwand'
scenario_comments['Wettable powders in water-soluble packaging']['Gardens / Trees']['Hose-end Sprayer']['ft2'] = 'Surrogate data:  ready-to-use hose-end sprayer'
scenario_comments['Wettable powders in water-soluble packaging']['Gardens / Trees']['Hose-end Sprayer']['gallons'] = 'Surrogate data:  ready-to-use hose-end sprayer'
scenario_comments['Wettable powders in water-soluble packaging']['Lawns / Turf']['Hose-end Sprayer'][''] = 'Surrogate data:  ready-to-use hose-end sprayer'
scenario_comments['Wettable powders in water-soluble packaging']['Lawns / Turf']['Manually-pressurized handwand'][''] = 'Surrogate data:  liquid concentrates with manually-pressurized handwand'
scenario_comments['Wettable powders in water-soluble packaging']['Lawns / Turf']['Backpack'][''] = 'Surrogate data:  liquid concentrates with manually-pressurized handwand'
scenario_comments['Wettable powders in water-soluble packaging']['Gardens / Trees']['Sprinkler can']['ft2'] = 'Surrogate data:  ready-to-use hose-end sprayer'
scenario_comments['Wettable powders in water-soluble packaging']['Gardens / Trees']['Sprinkler can']['gallons'] = 'Surrogate data:  ready-to-use hose-end sprayer'
scenario_comments['Wettable powders in water-soluble packaging']['Lawns / Turf']['Sprinkler can'][''] = 'Surrogate data:  ready-to-use hose-end sprayer'
scenario_comments['Wettable powders in water-soluble packaging']['Gardens / Trees']['Backpack'][''] = 'Surrogate data:  liquid concentrates with manually-pressurized handwand'
scenario_comments['Water-disersible Granule / Dry Flowable']['Lawns / Turf']['Manually-pressurized handwand'][''] = 'Surrogate data:  wettable powders with manually-pressurized handwand'
scenario_comments['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Hose-end Sprayer']['ft2'] = 'Surrogate data:  liquid concentrate with hose-end sprayer'
scenario_comments['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Hose-end Sprayer']['gallons'] = 'Surrogate data:  liquid concentrate with hose-end sprayer'
scenario_comments['Water-disersible Granule / Dry Flowable']['Lawns / Turf']['Hose-end Sprayer'][''] = 'Surrogate data:  liquid concentrate with hose-end sprayer'
scenario_comments['Wettable powders in water-soluble packaging']['Gardens / Trees']['Backpack'][''] = 'Surrogate data:  liquid concentrates with manually-pressurized handwand'
scenario_comments['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Manually-pressurized handwand']['ft2'] = 'Surrogate data:  wettable powders with manually-pressurized handwand'
scenario_comments['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Manually-pressurized handwand']['gallons'] = 'Surrogate data:  wettable powders with manually-pressurized handwand'
scenario_comments['Water-disersible Granule / Dry Flowable']['Lawns / Turf']['Backpack'][''] = 'Surrogate data:  wettable powders with manually-pressurized handwand'
scenario_comments['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Sprinkler can']['ft2'] = 'Surrogate data:  liquid concentrate with hose-end sprayer'
scenario_comments['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Sprinkler can']['gallons'] = 'Surrogate data:  liquid concentrate with hose-end sprayer'
scenario_comments['Water-disersible Granule / Dry Flowable']['Lawns / Turf']['Sprinkler can'][''] = 'Surrogate data:  liquid concentrate with hose-end sprayer'
scenario_comments['Granule']['Gardens / Trees']['Push-type rotary spreader'][''] = ''
scenario_comments['Granule']['Lawns / Turf']['Push-type rotary spreader'][''] = ''
scenario_comments['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Backpack']['ft2'] = 'Surrogate data:  wettable powders with manually-pressurized handwand'
scenario_comments['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Backpack']['gallons'] = 'Surrogate data:  wettable powders with manually-pressurized handwand'
scenario_comments['Granule']['Lawns / Turf']['Belly grinder'][''] = ''
scenario_comments['Granule']['Gardens / Trees']['Spoon'][''] = ''
scenario_comments['Granule']['Lawns / Turf']['Spoon'][''] = ''
scenario_comments['Granule']['Gardens / Trees']['Cup'][''] = ''
scenario_comments['Granule']['Lawns / Turf']['Cup'][''] = ''
scenario_comments['Granule']['Gardens / Trees']['Hand dispersal'][''] = ''
scenario_comments['Granule']['Lawns / Turf']['Hand dispersal'][''] = ''
scenario_comments['Granule']['Gardens / Trees']['Shaker can']['can'] = 'Surrogate data:  granules with cup'
scenario_comments['Granule']['Gardens / Trees']['Shaker can']['ft2'] = 'Surrogate data:  granules with cup'
scenario_comments['Granule']['Lawns / Turf']['Shaker can'][''] = 'Surrogate data:  granules with cup'
scenario_comments['Microencapsulated']['Gardens / Trees']['Manually-pressurized handwand']['ft2'] = 'Surrogate data:  liquid concentrates with manually-pressurized handwand'
scenario_comments['Microencapsulated']['Gardens / Trees']['Manually-pressurized handwand']['gallons'] = 'Surrogate data:  liquid concentrates with manually-pressurized handwand'
scenario_comments['Microencapsulated']['Gardens / Trees']['Hose-end Sprayer']['ft2'] = 'Surrogate data:  liquid concentrate with hose-end sprayer'
scenario_comments['Microencapsulated']['Gardens / Trees']['Hose-end Sprayer']['gallons'] = 'Surrogate data:  liquid concentrate with hose-end sprayer'
scenario_comments['Microencapsulated']['Lawns / Turf']['Hose-end Sprayer'][''] = 'Surrogate data:  liquid concentrate with hose-end sprayer'
scenario_comments['Microencapsulated']['Lawns / Turf']['Manually-pressurized handwand'][''] = 'Surrogate data:  liquid concentrates with manually-pressurized handwand'
scenario_comments['Microencapsulated']['Gardens / Trees']['Backpack']['ft2'] = 'Surrogate data:  liquid concentrates with backpack'
scenario_comments['Microencapsulated']['Gardens / Trees']['Backpack']['gallons'] = 'Surrogate data:  liquid concentrates with backpack'
scenario_comments['Microencapsulated']['Lawns / Turf']['Backpack'][''] = 'Surrogate data:  liquid concentrates with backpack'
scenario_comments['Microencapsulated']['Gardens / Trees']['Sprinkler can']['ft2'] = 'Surrogate data:  liquid concentrate with hose-end sprayer'
scenario_comments['Microencapsulated']['Gardens / Trees']['Sprinkler can']['gallons'] = 'Surrogate data:  liquid concentrate with hose-end sprayer'
scenario_comments['Microencapsulated']['Lawns / Turf']['Sprinkler can'][''] = 'Surrogate data:  liquid concentrate with hose-end sprayer'
scenario_comments['Ready-to-use']['Paints / Preservatives']['Aerosol can'][''] = ''
scenario_comments['Paints / Preservatives/ Stains']['Paints / Preservatives']['Airless Sprayer'][''] = ''
scenario_comments['Paints / Preservatives/ Stains']['Paints / Preservatives']['Brush'][''] = ''
scenario_comments['Paints / Preservatives/ Stains']['Paints / Preservatives']['Manually-pressurized handwand'][''] = ''
scenario_comments['Paints / Preservatives/ Stains']['Paints / Preservatives']['Roller'][''] = 'Surrogate data:  brush'
scenario_comments['Liquid concentrate']['Treated Pets']['Dip'][''] = ''
scenario_comments['Liquid concentrate']['Treated Pets']['Sponge'][''] = ''
scenario_comments['Ready-to-use']['Treated Pets']['Trigger-spray bottle'][''] = ''
scenario_comments['Ready-to-use']['Treated Pets']['Aerosol can'][''] = 'Surrogate data:  RTU trigger-spray bottle on pets'
scenario_comments['Ready-to-use']['Treated Pets']['Shampoo'][''] = ''
scenario_comments['Ready-to-use']['Treated Pets']['Spot-on'][''] = ''
scenario_comments['Ready-to-use']['Treated Pets']['Collar'][''] = 'Surrogate data:  spot-on'
scenario_comments['Dust/Powder']['Treated Pets']['Shaker Can'][''] = ''


application_rate_units['Dust/Powder']['Indoor Environment']['Plunger Duster']['Broadcast; Perimeter/Spot/ Bedbug (course application)'] = 'lb ai/lb dust'
application_rate_units['Dust/Powder']['Gardens / Trees']['Plunger Duster'][''] = 'lb ai/ft2'
application_rate_units['Dust/Powder']['Indoor Environment']['Bulb duster']['Perimeter/Spot/Bedbug; Crack and Crevice'] = 'lb ai/lb dust'
application_rate_units['Dust/Powder']['Gardens / Trees']['Bulb duster'][''] = 'lb ai/ft2'
application_rate_units['Dust/Powder']['Indoor Environment']['Electric/power duster']['Broadcast; Perimeter/Spot/ Bedbug (course application)'] = 'lb ai/lb dust'
application_rate_units['Dust/Powder']['Gardens / Trees']['Electric/power duster'][''] = 'lb ai/ft2'
application_rate_units['Dust/Powder']['Indoor Environment']['Hand crank duster']['Broadcast; Perimeter/Spot/ Bedbug (course application)'] = 'lb ai/lb dust'
application_rate_units['Dust/Powder']['Gardens / Trees']['Hand crank duster'][''] = 'lb ai/ft2'
application_rate_units['Dust/Powder']['Indoor Environment']['Shaker can']['Broadcast'] = 'lb ai/can'
application_rate_units['Dust/Powder']['Indoor Environment']['Shaker can']['Broadcast; Perimeter/Spot/ Bedbug (course application)'] = 'lb ai/can'
application_rate_units['Dust/Powder']['Gardens / Trees']['Shaker can']['can'] = 'lb ai/can'
application_rate_units['Dust/Powder']['Gardens / Trees']['Shaker can']['ft2'] = 'lb ai/ft2'
application_rate_units['Liquid concentrate']['Indoor Environment']['Manually-pressurized handwand (w/ or w/o pin stream nozzle)']['Broadcast, Perimeter/Spot/ Bedbug (course application); Perimeter /Spot/ Bedbug (pinstream application); Crack and Crevice'] = 'lb ai/gallon'
application_rate_units['Liquid concentrate']['Gardens / Trees']['Manually-pressurized handwand']['gallons'] = 'lb ai/gallon'
application_rate_units['Liquid concentrate']['Gardens / Trees']['Manually-pressurized handwand']['ft2'] = 'lb ai/ft2'
application_rate_units['Liquid concentrate']['Gardens / Trees']['Hose-end Sprayer']['ft2'] = 'lb ai/ft2'
application_rate_units['Liquid concentrate']['Gardens / Trees']['Hose-end Sprayer']['gallons'] = 'lb ai/gallon'
application_rate_units['Liquid concentrate']['Lawns / Turf']['Hose-end Sprayer'][''] = 'lb ai/acre'
application_rate_units['Liquid concentrate']['Lawns / Turf']['Manually-pressurized handwand'][''] = 'lb ai/gallon'
application_rate_units['Liquid concentrate']['Gardens / Trees']['Backpack']['ft2'] = 'lb ai/ft2'
application_rate_units['Liquid concentrate']['Gardens / Trees']['Backpack']['gallons'] = 'lb ai/gallon'
application_rate_units['Liquid concentrate']['Gardens / Trees']['Sprinkler can']['ft2'] = 'lb ai/ft2'
application_rate_units['Liquid concentrate']['Gardens / Trees']['Sprinkler can']['gallons'] = 'lb ai/gallon'
application_rate_units['Liquid concentrate']['Lawns / Turf']['Sprinkler can'][''] = 'lb ai/ft2'
application_rate_units['Ready-to-use']['Indoor Environment']['Aerosol can']['Broadcast Surface Spray'] = 'lb ai/16-oz can'
application_rate_units['Ready-to-use']['Indoor Environment']['Aerosol can']['Perimeter/ Spot/ Bedbug (course application)'] = 'lb ai/16-oz can'
application_rate_units['Ready-to-use']['Indoor Environment']['Aerosol can with pin stream nozzle']['Perimeter/ Spot/ Bedbug (pin stream application); Crack and Crevice'] = 'lb ai/16-oz can'
application_rate_units['Ready-to-use']['Indoor Environment']['Aerosol can']['Space spray'] = 'lb ai/16-oz can'

application_rate_units['Ready-to-use']['Insect Repellent']['Aerosol can'][''] = 'lb ai/can'
application_rate_units['Ready-to-use']['Insect Repellent']['Trigger-spray bottle'][''] = 'lb ai/bottle'

application_rate_units['Ready-to-use']['Gardens / Trees']['Aerosol can'][''] = 'lb ai/can'
application_rate_units['Ready-to-use']['Lawns / Turf']['Aerosol can'][''] = 'lb ai/can'
application_rate_units['Ready-to-use']['Indoor Environment']['Trigger-spray bottle']['Broadcast'] = 'lb ai/bottle'
application_rate_units['Ready-to-use']['Indoor Environment']['Trigger-spray bottle']['Perimeter/ Spot/ Bedbug (course application)'] = 'lb ai/bottle'

application_rate_units['Ready-to-use']['Gardens / Trees']['Trigger-spray bottle'][''] = 'lb ai/bottle'
application_rate_units['Ready-to-use']['Lawns / Turf']['Trigger-spray bottle'][''] = 'lb ai/bottle'
application_rate_units['Ready-to-use']['Indoor Environment']['Gels']['No exposure data available for this application scenario; however, exposure is considered negligible.'] = ''
application_rate_units['Ready-to-use']['Indoor Environment']['Pastes']['No exposure data available for this application scenario; however, exposure is considered negligible.'] = ''
application_rate_units['Ready-to-use']['Indoor Environment']['Foams']['No exposure data available for this application scenario; however, exposure is considered negligible.'] = ''
application_rate_units['Ready-to-use']['Indoor Environment']['Bait (granular, hand dispersal)'][''] = 'lb ai/ft2'
application_rate_units['Ready-to-use']['Indoor Environment']['Bait station / trap (enclosed in child resistant packaging)']['No exposure data available for this application scenario; however, exposure is considered negligible.'] = ''
application_rate_units['Ready-to-use']['Indoor Environment']['Pest strip']['No exposure data available for this application scenario; however, exposure is considered negligible.'] = ''
application_rate_units['Ready-to-use']['Gardens / Trees']['Hose-end Sprayer']['ft2'] = 'lb ai/ft2'
application_rate_units['Ready-to-use']['Gardens / Trees']['Hose-end Sprayer']['gallons'] = 'lb ai/gallon'
application_rate_units['Ready-to-use']['Lawns / Turf']['Hose-end Sprayer'][''] = 'lb ai/acre'
application_rate_units['Wettable powders']['Indoor Environment']['Manually-pressurized handwand (w/ or w/o pin stream nozzle)']['Broadcast, Perimeter/Spot/ Bedbug (course application); Perimeter /Spot/ Bedbug (pinstream application); Crack and Crevice'] = 'lb ai/gallon'
application_rate_units['Liquid concentrate']['Lawns / Turf']['Backpack'][''] = 'lb ai/gallon'
application_rate_units['Wettable powders']['Gardens / Trees']['Manually-pressurized handwand']['ft2'] = 'lb ai/ft2'
application_rate_units['Wettable powders']['Gardens / Trees']['Manually-pressurized handwand']['gallons'] = 'lb ai/gallon'
application_rate_units['Wettable powders']['Gardens / Trees']['Hose-end Sprayer']['ft2'] = 'lb ai/ft2'
application_rate_units['Wettable powders']['Gardens / Trees']['Hose-end Sprayer']['gallons'] = 'lb ai/gallon'
application_rate_units['Wettable powders']['Lawns / Turf']['Hose-end Sprayer'][''] = 'lb ai/acre'
application_rate_units['Wettable powders']['Lawns / Turf']['Manually-pressurized handwand'][''] = 'lb ai/gallon'
application_rate_units['Wettable powders']['Gardens / Trees']['Backpack']['ft2'] = 'lb ai/ft2'
application_rate_units['Wettable powders']['Gardens / Trees']['Backpack']['gallons'] = 'lb ai/gallon'
application_rate_units['Wettable powders']['Gardens / Trees']['Sprinkler can']['ft2'] = 'lb ai/ft2'
application_rate_units['Wettable powders']['Gardens / Trees']['Sprinkler can']['gallons'] = 'lb ai/gallon'
application_rate_units['Wettable powders']['Lawns / Turf']['Sprinkler can'][''] = 'lb ai/ft2'
application_rate_units['Wettable powders in water-soluble packaging']['Indoor Environment']['Manually-pressurized handwand (w/ or w/o pin stream nozzle)']['Broadcast, Perimeter/Spot/ Bedbug (course application); Perimeter /Spot/ Bedbug (pinstream application); Crack and Crevice'] = 'lb ai/gallon'
application_rate_units['Wettable powders']['Lawns / Turf']['Backpack'][''] = 'lb ai/gallon'
application_rate_units['Wettable powders in water-soluble packaging']['Gardens / Trees']['Manually-pressurized handwand']['ft2'] = 'lb ai/ft2'
application_rate_units['Wettable powders in water-soluble packaging']['Gardens / Trees']['Manually-pressurized handwand']['gallons'] = 'lb ai/gallon'
application_rate_units['Wettable powders in water-soluble packaging']['Gardens / Trees']['Hose-end Sprayer']['ft2'] = 'lb ai/ft2'
application_rate_units['Wettable powders in water-soluble packaging']['Gardens / Trees']['Hose-end Sprayer']['gallons'] = 'lb ai/gallon'
application_rate_units['Wettable powders in water-soluble packaging']['Lawns / Turf']['Hose-end Sprayer'][''] = 'lb ai/acre'
application_rate_units['Wettable powders in water-soluble packaging']['Lawns / Turf']['Manually-pressurized handwand'][''] = 'lb ai/gallon'
application_rate_units['Wettable powders in water-soluble packaging']['Lawns / Turf']['Backpack'][''] = 'lb ai/gallon'
application_rate_units['Wettable powders in water-soluble packaging']['Gardens / Trees']['Sprinkler can']['ft2'] = 'lb ai/ft2'
application_rate_units['Wettable powders in water-soluble packaging']['Gardens / Trees']['Sprinkler can']['gallons'] = 'lb ai/gallon'
application_rate_units['Wettable powders in water-soluble packaging']['Lawns / Turf']['Sprinkler can'][''] = 'lb ai/ft2'
application_rate_units['Wettable powders in water-soluble packaging']['Gardens / Trees']['Backpack'][''] = 'lb ai/ft2'
application_rate_units['Water-disersible Granule / Dry Flowable']['Lawns / Turf']['Manually-pressurized handwand'][''] = 'lb ai/gallon'
application_rate_units['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Hose-end Sprayer']['ft2'] = 'lb ai/ft2'
application_rate_units['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Hose-end Sprayer']['gallons'] = 'lb ai/gallon'
application_rate_units['Water-disersible Granule / Dry Flowable']['Lawns / Turf']['Hose-end Sprayer'][''] = 'lb ai/acre'
application_rate_units['Wettable powders in water-soluble packaging']['Gardens / Trees']['Backpack'][''] = 'lb ai/gallon'
application_rate_units['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Manually-pressurized handwand']['ft2'] = 'lb ai/ft2'
application_rate_units['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Manually-pressurized handwand']['gallons'] = 'lb ai/gallon'
application_rate_units['Water-disersible Granule / Dry Flowable']['Lawns / Turf']['Backpack'][''] = 'lb ai/gallon'
application_rate_units['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Sprinkler can']['ft2'] = 'lb ai/ft2'
application_rate_units['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Sprinkler can']['gallons'] = 'lb ai/gallon'
application_rate_units['Water-disersible Granule / Dry Flowable']['Lawns / Turf']['Sprinkler can'][''] = 'lb ai/ft2'
application_rate_units['Granule']['Gardens / Trees']['Push-type rotary spreader'][''] = 'lb ai/ft2'
application_rate_units['Granule']['Lawns / Turf']['Push-type rotary spreader'][''] = 'lb ai/acre'
application_rate_units['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Backpack']['ft2'] = 'lb ai/ft2'
application_rate_units['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Backpack']['gallons'] = 'lb ai/gallon'
application_rate_units['Granule']['Lawns / Turf']['Belly grinder'][''] = 'lb ai/ft2'
application_rate_units['Granule']['Gardens / Trees']['Spoon'][''] = 'lb ai/ft2'
application_rate_units['Granule']['Lawns / Turf']['Spoon'][''] = 'lb ai/ft2'
application_rate_units['Granule']['Gardens / Trees']['Cup'][''] = 'lb ai/ft2'
application_rate_units['Granule']['Lawns / Turf']['Cup'][''] = 'lb ai/ft2'
application_rate_units['Granule']['Gardens / Trees']['Hand dispersal'][''] = 'lb ai/ft2'
application_rate_units['Granule']['Lawns / Turf']['Hand dispersal'][''] = 'lb ai/ft2'
application_rate_units['Granule']['Gardens / Trees']['Shaker can']['can'] = 'lb ai/can'
application_rate_units['Granule']['Gardens / Trees']['Shaker can']['ft2'] = 'lb ai/ft2'
application_rate_units['Granule']['Lawns / Turf']['Shaker can'][''] = 'lb ai/ft2'
application_rate_units['Microencapsulated']['Gardens / Trees']['Manually-pressurized handwand']['ft2'] = 'lb ai/ft2'
application_rate_units['Microencapsulated']['Gardens / Trees']['Manually-pressurized handwand']['gallons'] = 'lb ai/gallon'
application_rate_units['Microencapsulated']['Gardens / Trees']['Hose-end Sprayer']['ft2'] = 'lb ai/ft2'
application_rate_units['Microencapsulated']['Gardens / Trees']['Hose-end Sprayer']['gallons'] = 'lb ai/gallon'
application_rate_units['Microencapsulated']['Lawns / Turf']['Hose-end Sprayer'][''] = 'lb ai/acre'
application_rate_units['Microencapsulated']['Lawns / Turf']['Manually-pressurized handwand'][''] = 'lb ai/gallon'
application_rate_units['Microencapsulated']['Gardens / Trees']['Backpack']['ft2'] = 'lb ai/ft2'
application_rate_units['Microencapsulated']['Gardens / Trees']['Backpack']['gallons'] = 'lb ai/gallon'
application_rate_units['Microencapsulated']['Lawns / Turf']['Backpack'][''] = 'lb ai/gallon'
application_rate_units['Microencapsulated']['Gardens / Trees']['Sprinkler can']['ft2'] = 'lb ai/ft2'
application_rate_units['Microencapsulated']['Gardens / Trees']['Sprinkler can']['gallons'] = 'lb ai/gallon'
application_rate_units['Microencapsulated']['Lawns / Turf']['Sprinkler can'][''] = 'lb ai/ft2'
application_rate_units['Ready-to-use']['Paints / Preservatives']['Aerosol can'][''] = 'lb ai/12-oz can'
application_rate_units['Paints / Preservatives/ Stains']['Paints / Preservatives']['Airless Sprayer'][''] = 'lb ai/1-gal can'
application_rate_units['Paints / Preservatives/ Stains']['Paints / Preservatives']['Brush'][''] = 'lb ai/1-gal can'
application_rate_units['Paints / Preservatives/ Stains']['Paints / Preservatives']['Manually-pressurized handwand'][''] = 'lb ai/1-gal can'
application_rate_units['Paints / Preservatives/ Stains']['Paints / Preservatives']['Roller'][''] = 'lb ai/1-gal can'
application_rate_units['Liquid concentrate']['Treated Pets']['Dip'][''] = 'lb ai/pet'
application_rate_units['Liquid concentrate']['Treated Pets']['Sponge'][''] = 'lb ai/pet'
application_rate_units['Ready-to-use']['Treated Pets']['Trigger-spray bottle'][''] = 'lb ai/pet'
application_rate_units['Ready-to-use']['Treated Pets']['Aerosol can'][''] = 'lb ai/pet'
application_rate_units['Ready-to-use']['Treated Pets']['Shampoo'][''] = 'lb ai/pet'
application_rate_units['Ready-to-use']['Treated Pets']['Spot-on'][''] = 'lb ai/pet'
application_rate_units['Ready-to-use']['Treated Pets']['Collar'][''] = 'lb ai/pet'
application_rate_units['Dust/Powder']['Treated Pets']['Shaker Can'][''] = 'lb ai/pet'



daily_usage['Dust/Powder']['Indoor Environment']['Plunger Duster']['Broadcast; Perimeter/Spot/ Bedbug (course application)'] = 0.5
daily_usage['Dust/Powder']['Gardens / Trees']['Plunger Duster'][''] = 1200
daily_usage['Dust/Powder']['Indoor Environment']['Bulb duster']['Perimeter/Spot/Bedbug; Crack and Crevice'] = 0.25
daily_usage['Dust/Powder']['Gardens / Trees']['Bulb duster'][''] = 1200
daily_usage['Dust/Powder']['Indoor Environment']['Electric/power duster']['Broadcast; Perimeter/Spot/ Bedbug (course application)'] = 0.5
daily_usage['Dust/Powder']['Gardens / Trees']['Electric/power duster'][''] = 1200
daily_usage['Dust/Powder']['Indoor Environment']['Hand crank duster']['Broadcast; Perimeter/Spot/ Bedbug (course application)'] = 0.5
daily_usage['Dust/Powder']['Gardens / Trees']['Hand crank duster'][''] = 1200
daily_usage['Dust/Powder']['Indoor Environment']['Shaker can']['Broadcast'] = 1
daily_usage['Dust/Powder']['Indoor Environment']['Shaker can']['Broadcast; Perimeter/Spot/ Bedbug (course application)'] = 0.5
daily_usage['Dust/Powder']['Gardens / Trees']['Shaker can']['can'] = 2
daily_usage['Dust/Powder']['Gardens / Trees']['Shaker can']['ft2'] = 1200
daily_usage['Liquid concentrate']['Indoor Environment']['Manually-pressurized handwand (w/ or w/o pin stream nozzle)']['Broadcast, Perimeter/Spot/ Bedbug (course application); Perimeter /Spot/ Bedbug (pinstream application); Crack and Crevice'] = 0.5
daily_usage['Liquid concentrate']['Gardens / Trees']['Manually-pressurized handwand']['gallons'] = 5
daily_usage['Liquid concentrate']['Gardens / Trees']['Manually-pressurized handwand']['ft2'] = 1200
daily_usage['Liquid concentrate']['Gardens / Trees']['Hose-end Sprayer']['ft2'] = 1200
daily_usage['Liquid concentrate']['Gardens / Trees']['Hose-end Sprayer']['gallons'] = 11
daily_usage['Liquid concentrate']['Lawns / Turf']['Hose-end Sprayer'][''] = 0.5
daily_usage['Liquid concentrate']['Lawns / Turf']['Manually-pressurized handwand'][''] = 5
daily_usage['Liquid concentrate']['Gardens / Trees']['Backpack']['ft2'] = 1200
daily_usage['Liquid concentrate']['Gardens / Trees']['Backpack']['gallons'] = 5
daily_usage['Liquid concentrate']['Gardens / Trees']['Sprinkler can']['ft2'] = 1200
daily_usage['Liquid concentrate']['Gardens / Trees']['Sprinkler can']['gallons'] = 5
daily_usage['Liquid concentrate']['Lawns / Turf']['Sprinkler can'][''] = 1000
daily_usage['Ready-to-use']['Indoor Environment']['Aerosol can']['Broadcast Surface Spray'] = 1
daily_usage['Ready-to-use']['Indoor Environment']['Aerosol can']['Perimeter/ Spot/ Bedbug (course application)'] = 0.5
daily_usage['Ready-to-use']['Indoor Environment']['Aerosol can with pin stream nozzle']['Perimeter/ Spot/ Bedbug (pin stream application); Crack and Crevice'] = 0.5
daily_usage['Ready-to-use']['Indoor Environment']['Aerosol can']['Space spray'] = 0.25


daily_usage['Ready-to-use']['Gardens / Trees']['Aerosol can'][''] = 2
daily_usage['Ready-to-use']['Lawns / Turf']['Aerosol can'][''] = 1
daily_usage['Ready-to-use']['Indoor Environment']['Trigger-spray bottle']['Broadcast'] = 1
daily_usage['Ready-to-use']['Indoor Environment']['Trigger-spray bottle']['Perimeter/ Spot/ Bedbug (course application)'] = 0.5

daily_usage['Ready-to-use']['Gardens / Trees']['Trigger-spray bottle'][''] = 2
daily_usage['Ready-to-use']['Lawns / Turf']['Trigger-spray bottle'][''] = 1
daily_usage['Ready-to-use']['Indoor Environment']['Gels']['No exposure data available for this application scenario; however, exposure is considered negligible.'] = 0
daily_usage['Ready-to-use']['Indoor Environment']['Pastes']['No exposure data available for this application scenario; however, exposure is considered negligible.'] = 0
daily_usage['Ready-to-use']['Indoor Environment']['Foams']['No exposure data available for this application scenario; however, exposure is considered negligible.'] = 0
daily_usage['Ready-to-use']['Indoor Environment']['Bait (granular, hand dispersal)'][''] = 0 #Not provided in SOP
daily_usage['Ready-to-use']['Indoor Environment']['Bait station / trap (enclosed in child resistant packaging)']['No exposure data available for this application scenario; however, exposure is considered negligible.'] = 0
daily_usage['Ready-to-use']['Indoor Environment']['Pest strip']['No exposure data available for this application scenario; however, exposure is considered negligible.'] = 0
daily_usage['Ready-to-use']['Gardens / Trees']['Hose-end Sprayer']['ft2'] = 1200
daily_usage['Ready-to-use']['Gardens / Trees']['Hose-end Sprayer']['gallons'] = 11
daily_usage['Ready-to-use']['Lawns / Turf']['Hose-end Sprayer'][''] = 0.5
daily_usage['Wettable powders']['Indoor Environment']['Manually-pressurized handwand (w/ or w/o pin stream nozzle)']['Broadcast, Perimeter/Spot/ Bedbug (course application); Perimeter /Spot/ Bedbug (pinstream application); Crack and Crevice'] = 0.5
daily_usage['Liquid concentrate']['Lawns / Turf']['Backpack'][''] = 5
daily_usage['Wettable powders']['Gardens / Trees']['Manually-pressurized handwand']['ft2'] = 1200
daily_usage['Wettable powders']['Gardens / Trees']['Manually-pressurized handwand']['gallons'] = 5
daily_usage['Wettable powders']['Gardens / Trees']['Hose-end Sprayer']['ft2'] = 1200
daily_usage['Wettable powders']['Gardens / Trees']['Hose-end Sprayer']['gallons'] = 11
daily_usage['Wettable powders']['Lawns / Turf']['Hose-end Sprayer'][''] = 0.5
daily_usage['Wettable powders']['Lawns / Turf']['Manually-pressurized handwand'][''] = 5
daily_usage['Wettable powders']['Gardens / Trees']['Backpack']['ft2'] = 1200
daily_usage['Wettable powders']['Gardens / Trees']['Backpack']['gallons'] = 5
daily_usage['Wettable powders']['Gardens / Trees']['Sprinkler can']['ft2'] = 1200
daily_usage['Wettable powders']['Gardens / Trees']['Sprinkler can']['gallons'] = 5
daily_usage['Wettable powders']['Lawns / Turf']['Sprinkler can'][''] = 1000
daily_usage['Wettable powders in water-soluble packaging']['Indoor Environment']['Manually-pressurized handwand (w/ or w/o pin stream nozzle)']['Broadcast, Perimeter/Spot/ Bedbug (course application); Perimeter /Spot/ Bedbug (pinstream application); Crack and Crevice'] = 0.5
daily_usage['Wettable powders']['Lawns / Turf']['Backpack'][''] = 5
daily_usage['Wettable powders in water-soluble packaging']['Gardens / Trees']['Manually-pressurized handwand']['ft2'] = 1200
daily_usage['Wettable powders in water-soluble packaging']['Gardens / Trees']['Manually-pressurized handwand']['gallons'] = 5
daily_usage['Wettable powders in water-soluble packaging']['Gardens / Trees']['Hose-end Sprayer']['ft2'] = 1200
daily_usage['Wettable powders in water-soluble packaging']['Gardens / Trees']['Hose-end Sprayer']['gallons'] = 11
daily_usage['Wettable powders in water-soluble packaging']['Lawns / Turf']['Hose-end Sprayer'][''] = 0.5
daily_usage['Wettable powders in water-soluble packaging']['Lawns / Turf']['Manually-pressurized handwand'][''] = 5
daily_usage['Wettable powders in water-soluble packaging']['Lawns / Turf']['Backpack'][''] = 5
daily_usage['Wettable powders in water-soluble packaging']['Gardens / Trees']['Sprinkler can']['ft2'] = 1200
daily_usage['Wettable powders in water-soluble packaging']['Gardens / Trees']['Sprinkler can']['gallons'] = 5
daily_usage['Wettable powders in water-soluble packaging']['Lawns / Turf']['Sprinkler can'][''] = 1000
daily_usage['Wettable powders in water-soluble packaging']['Gardens / Trees']['Backpack'][''] = 1200
daily_usage['Water-disersible Granule / Dry Flowable']['Lawns / Turf']['Manually-pressurized handwand'][''] = 5
daily_usage['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Hose-end Sprayer']['ft2'] = 1200
daily_usage['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Hose-end Sprayer']['gallons'] = 11
daily_usage['Water-disersible Granule / Dry Flowable']['Lawns / Turf']['Hose-end Sprayer'][''] = 0.5
daily_usage['Wettable powders in water-soluble packaging']['Gardens / Trees']['Backpack'][''] = 5
daily_usage['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Manually-pressurized handwand']['ft2'] = 1200
daily_usage['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Manually-pressurized handwand']['gallons'] = 5
daily_usage['Water-disersible Granule / Dry Flowable']['Lawns / Turf']['Backpack'][''] = 5
daily_usage['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Sprinkler can']['ft2'] = 1200
daily_usage['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Sprinkler can']['gallons'] = 5
daily_usage['Water-disersible Granule / Dry Flowable']['Lawns / Turf']['Sprinkler can'][''] = 1000
daily_usage['Granule']['Gardens / Trees']['Push-type rotary spreader'][''] = 1200
daily_usage['Granule']['Lawns / Turf']['Push-type rotary spreader'][''] = 0.5
daily_usage['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Backpack']['ft2'] = 1200
daily_usage['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Backpack']['gallons'] = 5
daily_usage['Granule']['Lawns / Turf']['Belly grinder'][''] = 1200
daily_usage['Granule']['Gardens / Trees']['Spoon'][''] = 1200
daily_usage['Granule']['Lawns / Turf']['Spoon'][''] = 100
daily_usage['Granule']['Gardens / Trees']['Cup'][''] = 1200
daily_usage['Granule']['Lawns / Turf']['Cup'][''] = 100
daily_usage['Granule']['Gardens / Trees']['Hand dispersal'][''] = 1200
daily_usage['Granule']['Lawns / Turf']['Hand dispersal'][''] = 100
daily_usage['Granule']['Gardens / Trees']['Shaker can']['can'] = 2
daily_usage['Granule']['Gardens / Trees']['Shaker can']['ft2'] = 1200
daily_usage['Granule']['Lawns / Turf']['Shaker can'][''] = 100
daily_usage['Microencapsulated']['Gardens / Trees']['Manually-pressurized handwand']['ft2'] = 1200
daily_usage['Microencapsulated']['Gardens / Trees']['Manually-pressurized handwand']['gallons'] = 5
daily_usage['Microencapsulated']['Gardens / Trees']['Hose-end Sprayer']['ft2'] = 1200
daily_usage['Microencapsulated']['Gardens / Trees']['Hose-end Sprayer']['gallons'] = 11
daily_usage['Microencapsulated']['Lawns / Turf']['Hose-end Sprayer'][''] = 0.5
daily_usage['Microencapsulated']['Lawns / Turf']['Manually-pressurized handwand'][''] = 5
daily_usage['Microencapsulated']['Gardens / Trees']['Backpack']['ft2'] = 1200
daily_usage['Microencapsulated']['Gardens / Trees']['Backpack']['gallons'] = 5
daily_usage['Microencapsulated']['Lawns / Turf']['Backpack'][''] = 5
daily_usage['Microencapsulated']['Gardens / Trees']['Sprinkler can']['ft2'] = 1200
daily_usage['Microencapsulated']['Gardens / Trees']['Sprinkler can']['gallons'] = 5
daily_usage['Microencapsulated']['Lawns / Turf']['Sprinkler can'][''] = 1000
daily_usage['Ready-to-use']['Paints / Preservatives']['Aerosol can'][''] = 3
daily_usage['Paints / Preservatives/ Stains']['Paints / Preservatives']['Airless Sprayer'][''] = 5
daily_usage['Paints / Preservatives/ Stains']['Paints / Preservatives']['Brush'][''] = 2
daily_usage['Paints / Preservatives/ Stains']['Paints / Preservatives']['Manually-pressurized handwand'][''] = 3
daily_usage['Paints / Preservatives/ Stains']['Paints / Preservatives']['Roller'][''] = 2
daily_usage['Liquid concentrate']['Treated Pets']['Dip'][''] = 2
daily_usage['Liquid concentrate']['Treated Pets']['Sponge'][''] = 2
daily_usage['Ready-to-use']['Treated Pets']['Trigger-spray bottle'][''] = 2
daily_usage['Ready-to-use']['Treated Pets']['Aerosol can'][''] = 2
daily_usage['Ready-to-use']['Treated Pets']['Shampoo'][''] = 2
daily_usage['Ready-to-use']['Treated Pets']['Spot-on'][''] = 2
daily_usage['Ready-to-use']['Treated Pets']['Collar'][''] = 2
daily_usage['Dust/Powder']['Treated Pets']['Shaker Can'][''] = 2


daily_usage_units['Dust/Powder']['Indoor Environment']['Plunger Duster']['Broadcast; Perimeter/Spot/ Bedbug (course application)'] = 'lb dust'
daily_usage_units['Dust/Powder']['Gardens / Trees']['Plunger Duster'][''] = 'ft2'
daily_usage_units['Dust/Powder']['Indoor Environment']['Bulb duster']['Perimeter/Spot/Bedbug; Crack and Crevice'] = 'lb dust'
daily_usage_units['Dust/Powder']['Gardens / Trees']['Bulb duster'][''] = 'ft2'
daily_usage_units['Dust/Powder']['Indoor Environment']['Electric/power duster']['Broadcast; Perimeter/Spot/ Bedbug (course application)'] = 'lb dust'
daily_usage_units['Dust/Powder']['Gardens / Trees']['Electric/power duster'][''] = 'ft2'
daily_usage_units['Dust/Powder']['Indoor Environment']['Hand crank duster']['Broadcast; Perimeter/Spot/ Bedbug (course application)'] = 'lb dust'
daily_usage_units['Dust/Powder']['Gardens / Trees']['Hand crank duster'][''] = 'ft2'
daily_usage_units['Dust/Powder']['Indoor Environment']['Shaker can']['Broadcast'] = 'can'
daily_usage_units['Dust/Powder']['Indoor Environment']['Shaker can']['Broadcast; Perimeter/Spot/ Bedbug (course application)'] = 'can'
daily_usage_units['Dust/Powder']['Gardens / Trees']['Shaker can'][''] = 'can'
daily_usage_units['Dust/Powder']['Gardens / Trees']['Shaker can'][''] = 'ft2'
daily_usage_units['Liquid concentrate']['Indoor Environment']['Manually-pressurized handwand (w/ or w/o pin stream nozzle)']['Broadcast, Perimeter/Spot/ Bedbug (course application); Perimeter /Spot/ Bedbug (pinstream application); Crack and Crevice'] = 'gallons'
daily_usage_units['Liquid concentrate']['Gardens / Trees']['Manually-pressurized handwand'][''] = 'gallons'
daily_usage_units['Liquid concentrate']['Gardens / Trees']['Manually-pressurized handwand'][''] = 'ft2'
daily_usage_units['Liquid concentrate']['Gardens / Trees']['Hose-end Sprayer'][''] = 'ft2'
daily_usage_units['Liquid concentrate']['Gardens / Trees']['Hose-end Sprayer'][''] = 'gallons'
daily_usage_units['Liquid concentrate']['Lawns / Turf']['Hose-end Sprayer'][''] = 'acres'
daily_usage_units['Liquid concentrate']['Lawns / Turf']['Manually-pressurized handwand'][''] = 'gallons'
daily_usage_units['Liquid concentrate']['Gardens / Trees']['Backpack'][''] = 'ft2'
daily_usage_units['Liquid concentrate']['Gardens / Trees']['Backpack'][''] = 'gallons'
daily_usage_units['Liquid concentrate']['Gardens / Trees']['Sprinkler can'][''] = 'ft2'
daily_usage_units['Liquid concentrate']['Gardens / Trees']['Sprinkler can'][''] = 'gallons'
daily_usage_units['Liquid concentrate']['Lawns / Turf']['Sprinkler can'][''] = 'ft2'
daily_usage_units['Ready-to-use']['Indoor Environment']['Aerosol can']['Broadcast Surface Spray'] = '16-oz can'
daily_usage_units['Ready-to-use']['Indoor Environment']['Aerosol can']['Perimeter/ Spot/ Bedbug (course application)'] = '16-oz can'
daily_usage_units['Ready-to-use']['Indoor Environment']['Aerosol can with pin stream nozzle']['Perimeter/ Spot/ Bedbug (pin stream application); Crack and Crevice'] = '16-oz can'
daily_usage_units['Ready-to-use']['Indoor Environment']['Aerosol can']['Space spray'] = '16-oz can'

daily_usage_units['Ready-to-use']['Insect Repellent']['Aerosol can'][''] = 'can'
daily_usage_units['Ready-to-use']['Insect Repellent']['Trigger-spray bottle'][''] = 'bottle'

daily_usage_units['Ready-to-use']['Gardens / Trees']['Aerosol can'][''] = 'can'
daily_usage_units['Ready-to-use']['Lawns / Turf']['Aerosol can'][''] = 'can'
daily_usage_units['Ready-to-use']['Indoor Environment']['Trigger-spray bottle']['Broadcast'] = 'bottle'
daily_usage_units['Ready-to-use']['Indoor Environment']['Trigger-spray bottle']['Perimeter/ Spot/ Bedbug (course application)'] = 'bottle'

daily_usage_units['Ready-to-use']['Gardens / Trees']['Trigger-spray bottle'][''] = 'bottle'
daily_usage_units['Ready-to-use']['Lawns / Turf']['Trigger-spray bottle'][''] = 'bottle'
daily_usage_units['Ready-to-use']['Indoor Environment']['Gels']['No exposure data available for this application scenario; however, exposure is considered negligible.'] = ''
daily_usage_units['Ready-to-use']['Indoor Environment']['Pastes']['No exposure data available for this application scenario; however, exposure is considered negligible.'] = ''
daily_usage_units['Ready-to-use']['Indoor Environment']['Foams']['No exposure data available for this application scenario; however, exposure is considered negligible.'] = ''
daily_usage_units['Ready-to-use']['Indoor Environment']['Bait (granular, hand dispersal)'][''] = 'ft2'
daily_usage_units['Ready-to-use']['Indoor Environment']['Bait station / trap (enclosed in child resistant packaging)']['No exposure data available for this application scenario; however, exposure is considered negligible.'] = ''
daily_usage_units['Ready-to-use']['Indoor Environment']['Pest strip']['No exposure data available for this application scenario; however, exposure is considered negligible.'] = ''
daily_usage_units['Ready-to-use']['Gardens / Trees']['Hose-end Sprayer'][''] = 'ft2'
daily_usage_units['Ready-to-use']['Gardens / Trees']['Hose-end Sprayer'][''] = 'gallons'
daily_usage_units['Ready-to-use']['Lawns / Turf']['Hose-end Sprayer'][''] = 'acres'
daily_usage_units['Wettable powders']['Indoor Environment']['Manually-pressurized handwand (w/ or w/o pin stream nozzle)']['Broadcast, Perimeter/Spot/ Bedbug (course application); Perimeter /Spot/ Bedbug (pinstream application); Crack and Crevice'] = 'gallons'
daily_usage_units['Liquid concentrate']['Lawns / Turf']['Backpack'][''] = 'gallons'
daily_usage_units['Wettable powders']['Gardens / Trees']['Manually-pressurized handwand'][''] = 'ft2'
daily_usage_units['Wettable powders']['Gardens / Trees']['Manually-pressurized handwand'][''] = 'gallons'
daily_usage_units['Wettable powders']['Gardens / Trees']['Hose-end Sprayer'][''] = 'ft2'
daily_usage_units['Wettable powders']['Gardens / Trees']['Hose-end Sprayer'][''] = 'gallons'
daily_usage_units['Wettable powders']['Lawns / Turf']['Hose-end Sprayer'][''] = 'acres'
daily_usage_units['Wettable powders']['Lawns / Turf']['Manually-pressurized handwand'][''] = 'gallons'
daily_usage_units['Wettable powders']['Gardens / Trees']['Backpack'][''] = 'ft2'
daily_usage_units['Wettable powders']['Gardens / Trees']['Backpack'][''] = 'gallons'
daily_usage_units['Wettable powders']['Gardens / Trees']['Sprinkler can'][''] = 'ft2'
daily_usage_units['Wettable powders']['Gardens / Trees']['Sprinkler can'][''] = 'gallons'
daily_usage_units['Wettable powders']['Lawns / Turf']['Sprinkler can'][''] = 'ft2'
daily_usage_units['Wettable powders in water-soluble packaging']['Indoor Environment']['Manually-pressurized handwand (w/ or w/o pin stream nozzle)']['Broadcast, Perimeter/Spot/ Bedbug (course application); Perimeter /Spot/ Bedbug (pinstream application); Crack and Crevice'] = 'gallons'
daily_usage_units['Wettable powders']['Lawns / Turf']['Backpack'][''] = 'gallons'
daily_usage_units['Wettable powders in water-soluble packaging']['Gardens / Trees']['Manually-pressurized handwand'][''] = 'ft2'
daily_usage_units['Wettable powders in water-soluble packaging']['Gardens / Trees']['Manually-pressurized handwand'][''] = 'gallons'
daily_usage_units['Wettable powders in water-soluble packaging']['Gardens / Trees']['Hose-end Sprayer'][''] = 'ft2'
daily_usage_units['Wettable powders in water-soluble packaging']['Gardens / Trees']['Hose-end Sprayer'][''] = 'gallons'
daily_usage_units['Wettable powders in water-soluble packaging']['Lawns / Turf']['Hose-end Sprayer'][''] = 'acres'
daily_usage_units['Wettable powders in water-soluble packaging']['Lawns / Turf']['Manually-pressurized handwand'][''] = 'gallons'
daily_usage_units['Wettable powders in water-soluble packaging']['Lawns / Turf']['Backpack'][''] = 'gallons'
daily_usage_units['Wettable powders in water-soluble packaging']['Gardens / Trees']['Sprinkler can'][''] = 'ft2'
daily_usage_units['Wettable powders in water-soluble packaging']['Gardens / Trees']['Sprinkler can'][''] = 'gallons'
daily_usage_units['Wettable powders in water-soluble packaging']['Lawns / Turf']['Sprinkler can'][''] = 'ft2'
daily_usage_units['Wettable powders in water-soluble packaging']['Gardens / Trees']['Backpack'][''] = 'ft2'
daily_usage_units['Water-disersible Granule / Dry Flowable']['Lawns / Turf']['Manually-pressurized handwand'][''] = 'gallons'
daily_usage_units['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Hose-end Sprayer'][''] = 'ft2'
daily_usage_units['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Hose-end Sprayer'][''] = 'gallons'
daily_usage_units['Water-disersible Granule / Dry Flowable']['Lawns / Turf']['Hose-end Sprayer'][''] = 'acres'
daily_usage_units['Wettable powders in water-soluble packaging']['Gardens / Trees']['Backpack'][''] = 'gallons'
daily_usage_units['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Manually-pressurized handwand'][''] = 'ft2'
daily_usage_units['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Manually-pressurized handwand'][''] = 'gallons'
daily_usage_units['Water-disersible Granule / Dry Flowable']['Lawns / Turf']['Backpack'][''] = 'gallons'
daily_usage_units['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Sprinkler can'][''] = 'ft2'
daily_usage_units['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Sprinkler can'][''] = 'gallons'
daily_usage_units['Water-disersible Granule / Dry Flowable']['Lawns / Turf']['Sprinkler can'][''] = 'ft2'
daily_usage_units['Granule']['Gardens / Trees']['Push-type rotary spreader'][''] = 'ft2'
daily_usage_units['Granule']['Lawns / Turf']['Push-type rotary spreader'][''] = 'acres'
daily_usage_units['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Backpack'][''] = 'ft2'
daily_usage_units['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Backpack'][''] = 'gallons'
daily_usage_units['Granule']['Lawns / Turf']['Belly grinder'][''] = 'ft2'
daily_usage_units['Granule']['Gardens / Trees']['Spoon'][''] = 'ft2'
daily_usage_units['Granule']['Lawns / Turf']['Spoon'][''] = 'ft2'
daily_usage_units['Granule']['Gardens / Trees']['Cup'][''] = 'ft2'
daily_usage_units['Granule']['Lawns / Turf']['Cup'][''] = 'ft2'
daily_usage_units['Granule']['Gardens / Trees']['Hand dispersal'][''] = 'ft2'
daily_usage_units['Granule']['Lawns / Turf']['Hand dispersal'][''] = 'ft2'
daily_usage_units['Granule']['Gardens / Trees']['Shaker can']['can'] = 'can'
daily_usage_units['Granule']['Gardens / Trees']['Shaker can']['ft2'] = 'ft2'
daily_usage_units['Granule']['Lawns / Turf']['Shaker can'][''] = 'ft2'
daily_usage_units['Microencapsulated']['Gardens / Trees']['Manually-pressurized handwand'][''] = 'ft2'
daily_usage_units['Microencapsulated']['Gardens / Trees']['Manually-pressurized handwand'][''] = 'gallons'
daily_usage_units['Microencapsulated']['Gardens / Trees']['Hose-end Sprayer'][''] = 'ft2'
daily_usage_units['Microencapsulated']['Gardens / Trees']['Hose-end Sprayer'][''] = 'gallons'
daily_usage_units['Microencapsulated']['Lawns / Turf']['Hose-end Sprayer'][''] = 'acres'
daily_usage_units['Microencapsulated']['Lawns / Turf']['Manually-pressurized handwand'][''] = 'gallons'
daily_usage_units['Microencapsulated']['Gardens / Trees']['Backpack'][''] = 'ft2'
daily_usage_units['Microencapsulated']['Gardens / Trees']['Backpack'][''] = 'gallons'
daily_usage_units['Microencapsulated']['Lawns / Turf']['Backpack'][''] = 'gallons'
daily_usage_units['Microencapsulated']['Gardens / Trees']['Sprinkler can'][''] = 'ft2'
daily_usage_units['Microencapsulated']['Gardens / Trees']['Sprinkler can'][''] = 'gallons'
daily_usage_units['Microencapsulated']['Lawns / Turf']['Sprinkler can'][''] = 'ft2'
daily_usage_units['Ready-to-use']['Paints / Preservatives']['Aerosol can'][''] = '12-oz can'
daily_usage_units['Paints / Preservatives/ Stains']['Paints / Preservatives']['Airless Sprayer'][''] = '1-gallon can'
daily_usage_units['Paints / Preservatives/ Stains']['Paints / Preservatives']['Brush'][''] = '1-gallon can'
daily_usage_units['Paints / Preservatives/ Stains']['Paints / Preservatives']['Manually-pressurized handwand'][''] = '1-gallon can'
daily_usage_units['Paints / Preservatives/ Stains']['Paints / Preservatives']['Roller'][''] = '1-gallon can'
daily_usage_units['Liquid concentrate']['Treated Pets']['Dip'][''] = 'pet'
daily_usage_units['Liquid concentrate']['Treated Pets']['Sponge'][''] = 'pet'
daily_usage_units['Ready-to-use']['Treated Pets']['Trigger-spray bottle'][''] = 'pet'
daily_usage_units['Ready-to-use']['Treated Pets']['Aerosol can'][''] = 'pet'
daily_usage_units['Ready-to-use']['Treated Pets']['Shampoo'][''] = 'pet'
daily_usage_units['Ready-to-use']['Treated Pets']['Spot-on'][''] = 'pet'
daily_usage_units['Ready-to-use']['Treated Pets']['Collar'][''] = 'pet'
daily_usage_units['Dust/Powder']['Treated Pets']['Shaker Can'][''] = 'pet'



unit_exposure['Dust/Powder']['Gardens / Trees']['Plunger Duster']['']['dermal'] = 250
unit_exposure['Dust/Powder']['Indoor Environment']['Bulb duster']['Perimeter/Spot/Bedbug; Crack and Crevice']['dermal'] = 250
unit_exposure['Dust/Powder']['Gardens / Trees']['Bulb duster']['']['dermal'] = 250
unit_exposure['Dust/Powder']['Indoor Environment']['Electric/power duster']['Broadcast; Perimeter/Spot/ Bedbug (course application)']['dermal'] = 4300
unit_exposure['Dust/Powder']['Gardens / Trees']['Electric/power duster']['']['dermal'] = 4300
unit_exposure['Dust/Powder']['Indoor Environment']['Hand crank duster']['Broadcast; Perimeter/Spot/ Bedbug (course application)']['dermal'] = 4300
unit_exposure['Dust/Powder']['Gardens / Trees']['Hand crank duster']['']['dermal'] = 4300
unit_exposure['Dust/Powder']['Indoor Environment']['Shaker can']['Broadcast']['dermal'] = 4300
unit_exposure['Dust/Powder']['Indoor Environment']['Shaker can']['Broadcast; Perimeter/Spot/ Bedbug (course application)']['dermal'] = 4300
unit_exposure['Dust/Powder']['Gardens / Trees']['Shaker can']['can']['dermal'] = 4300
unit_exposure['Dust/Powder']['Gardens / Trees']['Shaker can']['ft2']['dermal'] = 4300
unit_exposure['Liquid concentrate']['Indoor Environment']['Manually-pressurized handwand (w/ or w/o pin stream nozzle)']['Broadcast, Perimeter/Spot/ Bedbug (course application); Perimeter /Spot/ Bedbug (pinstream application); Crack and Crevice']['dermal'] = 69
unit_exposure['Liquid concentrate']['Gardens / Trees']['Manually-pressurized handwand']['ft2']['dermal'] = 63
unit_exposure['Liquid concentrate']['Gardens / Trees']['Manually-pressurized handwand']['gallons']['dermal'] = 63
unit_exposure['Liquid concentrate']['Gardens / Trees']['Hose-end Sprayer']['ft2']['dermal'] = 58
unit_exposure['Liquid concentrate']['Gardens / Trees']['Hose-end Sprayer']['gallons']['dermal'] = 58
unit_exposure['Liquid concentrate']['Lawns / Turf']['Hose-end Sprayer']['']['dermal'] = 13.4
unit_exposure['Liquid concentrate']['Lawns / Turf']['Manually-pressurized handwand']['']['dermal'] = 63
unit_exposure['Liquid concentrate']['Gardens / Trees']['Backpack']['ft2']['dermal'] = 130
unit_exposure['Liquid concentrate']['Gardens / Trees']['Backpack']['gallons']['dermal'] = 130
unit_exposure['Liquid concentrate']['Gardens / Trees']['Sprinkler can']['ft2']['dermal'] = 58
unit_exposure['Liquid concentrate']['Gardens / Trees']['Sprinkler can']['gallons']['dermal'] = 58
unit_exposure['Liquid concentrate']['Lawns / Turf']['Sprinkler can']['']['dermal'] = 13.4
unit_exposure['Ready-to-use']['Indoor Environment']['Aerosol can']['Broadcast Surface Spray']['dermal'] = 370
unit_exposure['Ready-to-use']['Indoor Environment']['Aerosol can']['Perimeter/ Spot/ Bedbug (course application)']['dermal'] = 370
unit_exposure['Ready-to-use']['Indoor Environment']['Aerosol can with pin stream nozzle']['Perimeter/ Spot/ Bedbug (pin stream application); Crack and Crevice']['dermal'] = 370
unit_exposure['Ready-to-use']['Indoor Environment']['Aerosol can']['Space spray']['dermal'] = 370
unit_exposure['Ready-to-use']['Gardens / Trees']['Aerosol can']['']['dermal'] = 370
unit_exposure['Ready-to-use']['Lawns / Turf']['Aerosol can']['']['dermal'] = 370
unit_exposure['Ready-to-use']['Indoor Environment']['Trigger-spray bottle']['Broadcast']['dermal'] = 85.1
unit_exposure['Ready-to-use']['Indoor Environment']['Trigger-spray bottle']['Perimeter/ Spot/ Bedbug (course application)']['dermal'] = 85.1
unit_exposure['Ready-to-use']['Gardens / Trees']['Trigger-spray bottle']['']['dermal'] = 85.1
unit_exposure['Ready-to-use']['Lawns / Turf']['Trigger-spray bottle']['']['dermal'] = 85.1
unit_exposure['Ready-to-use']['Indoor Environment']['Gels']['No exposure data available for this application scenario; however, exposure is considered negligible.']['dermal'] = 0
unit_exposure['Ready-to-use']['Indoor Environment']['Pastes']['No exposure data available for this application scenario; however, exposure is considered negligible.']['dermal'] = 0
unit_exposure['Ready-to-use']['Indoor Environment']['Foams']['No exposure data available for this application scenario; however, exposure is considered negligible.']['dermal'] = 0
unit_exposure['Ready-to-use']['Indoor Environment']['Bait (granular, hand dispersal)']['']['dermal'] = 160
unit_exposure['Ready-to-use']['Indoor Environment']['Bait station / trap (enclosed in child resistant packaging)']['No exposure data available for this application scenario; however, exposure is considered negligible.']['dermal'] = 0
unit_exposure['Ready-to-use']['Indoor Environment']['Pest strip']['No exposure data available for this application scenario; however, exposure is considered negligible.']['dermal'] = 0
unit_exposure['Ready-to-use']['Gardens / Trees']['Hose-end Sprayer']['gallons']['dermal'] = 6.26
unit_exposure['Ready-to-use']['Gardens / Trees']['Hose-end Sprayer']['ft2']['dermal'] = 6.26
unit_exposure['Ready-to-use']['Lawns / Turf']['Hose-end Sprayer']['']['dermal'] = 6.26
unit_exposure['Wettable powders']['Indoor Environment']['Manually-pressurized handwand (w/ or w/o pin stream nozzle)']['Broadcast, Perimeter/Spot/ Bedbug (course application); Perimeter /Spot/ Bedbug (pinstream application); Crack and Crevice']['dermal'] = 69
unit_exposure['Liquid concentrate']['Lawns / Turf']['Backpack']['']['dermal'] = 130
unit_exposure['Wettable powders']['Gardens / Trees']['Manually-pressurized handwand']['gallons']['dermal'] = 69
unit_exposure['Wettable powders']['Gardens / Trees']['Manually-pressurized handwand']['ft2']['dermal'] = 69
unit_exposure['Wettable powders']['Gardens / Trees']['Hose-end Sprayer']['gallons']['dermal'] = 58
unit_exposure['Wettable powders']['Gardens / Trees']['Hose-end Sprayer']['ft2']['dermal'] = 58
unit_exposure['Wettable powders']['Lawns / Turf']['Hose-end Sprayer']['']['dermal'] = 13.4
unit_exposure['Wettable powders']['Lawns / Turf']['Manually-pressurized handwand']['']['dermal'] = 69
unit_exposure['Wettable powders']['Gardens / Trees']['Backpack']['gallons']['dermal'] = 69
unit_exposure['Wettable powders']['Gardens / Trees']['Backpack']['ft2']['dermal'] = 69
unit_exposure['Wettable powders']['Gardens / Trees']['Sprinkler can']['gallons']['dermal'] = 58
unit_exposure['Wettable powders']['Gardens / Trees']['Sprinkler can']['ft2']['dermal'] = 58
unit_exposure['Wettable powders']['Lawns / Turf']['Sprinkler can']['']['dermal'] = 13.4
unit_exposure['Wettable powders in water-soluble packaging']['Indoor Environment']['Manually-pressurized handwand (w/ or w/o pin stream nozzle)']['Broadcast, Perimeter/Spot/ Bedbug (course application); Perimeter /Spot/ Bedbug (pinstream application); Crack and Crevice']['dermal'] = 69
unit_exposure['Wettable powders']['Lawns / Turf']['Backpack']['']['dermal'] = 69
unit_exposure['Wettable powders in water-soluble packaging']['Gardens / Trees']['Manually-pressurized handwand']['gallons']['dermal'] = 63
unit_exposure['Wettable powders in water-soluble packaging']['Gardens / Trees']['Manually-pressurized handwand']['ft2']['dermal'] = 63
unit_exposure['Wettable powders in water-soluble packaging']['Gardens / Trees']['Hose-end Sprayer']['gallons']['dermal'] = 6.26
unit_exposure['Wettable powders in water-soluble packaging']['Gardens / Trees']['Hose-end Sprayer']['ft2']['dermal'] = 6.26
unit_exposure['Wettable powders in water-soluble packaging']['Lawns / Turf']['Hose-end Sprayer']['']['dermal'] = 6.26
unit_exposure['Wettable powders in water-soluble packaging']['Lawns / Turf']['Manually-pressurized handwand']['']['dermal'] = 63
unit_exposure['Wettable powders in water-soluble packaging']['Lawns / Turf']['Backpack']['']['dermal'] = 63
unit_exposure['Wettable powders in water-soluble packaging']['Gardens / Trees']['Sprinkler can']['ft2']['dermal'] = 6.26
unit_exposure['Wettable powders in water-soluble packaging']['Gardens / Trees']['Sprinkler can']['gallons']['dermal'] = 6.26
unit_exposure['Wettable powders in water-soluble packaging']['Lawns / Turf']['Sprinkler can']['']['dermal'] = 6.26
unit_exposure['Wettable powders in water-soluble packaging']['Gardens / Trees']['Backpack']['']['dermal'] = 63
unit_exposure['Water-disersible Granule / Dry Flowable']['Lawns / Turf']['Manually-pressurized handwand']['']['dermal'] = 69
unit_exposure['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Hose-end Sprayer']['gallons']['dermal'] = 58
unit_exposure['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Hose-end Sprayer']['ft2']['dermal'] = 58
unit_exposure['Water-disersible Granule / Dry Flowable']['Lawns / Turf']['Hose-end Sprayer']['']['dermal'] = 13.4
unit_exposure['Wettable powders in water-soluble packaging']['Gardens / Trees']['Backpack']['']['dermal'] = 63
unit_exposure['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Manually-pressurized handwand']['gallons']['dermal'] = 69
unit_exposure['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Manually-pressurized handwand']['ft2']['dermal'] = 69
unit_exposure['Water-disersible Granule / Dry Flowable']['Lawns / Turf']['Backpack']['']['dermal'] = 69
unit_exposure['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Sprinkler can']['ft2']['dermal'] = 58
unit_exposure['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Sprinkler can']['gallons']['dermal'] = 58
unit_exposure['Water-disersible Granule / Dry Flowable']['Lawns / Turf']['Sprinkler can']['']['dermal'] = 13.4
unit_exposure['Granule']['Gardens / Trees']['Push-type rotary spreader']['']['dermal'] = 0.81
unit_exposure['Granule']['Lawns / Turf']['Push-type rotary spreader']['']['dermal'] = 0.81
unit_exposure['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Backpack']['ft2']['dermal'] = 69
unit_exposure['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Backpack']['gallons']['dermal'] = 69
unit_exposure['Granule']['Lawns / Turf']['Belly grinder']['']['dermal'] = 360
unit_exposure['Granule']['Gardens / Trees']['Spoon']['']['dermal'] = 6.2
unit_exposure['Granule']['Lawns / Turf']['Spoon']['']['dermal'] = 6.2
unit_exposure['Granule']['Gardens / Trees']['Cup']['']['dermal'] = 0.11
unit_exposure['Granule']['Lawns / Turf']['Cup']['']['dermal'] = 0.11
unit_exposure['Granule']['Gardens / Trees']['Hand dispersal']['']['dermal'] = 160
unit_exposure['Granule']['Lawns / Turf']['Hand dispersal']['']['dermal'] = 160
unit_exposure['Granule']['Gardens / Trees']['Shaker can']['can']['dermal'] = 0.11
unit_exposure['Granule']['Gardens / Trees']['Shaker can']['ft2']['dermal'] = 0.11
unit_exposure['Granule']['Lawns / Turf']['Shaker can']['']['dermal'] = 0.11
unit_exposure['Microencapsulated']['Gardens / Trees']['Manually-pressurized handwand']['gallons']['dermal'] = 63
unit_exposure['Microencapsulated']['Gardens / Trees']['Manually-pressurized handwand']['ft2']['dermal'] = 63
unit_exposure['Microencapsulated']['Gardens / Trees']['Hose-end Sprayer']['gallons']['dermal'] = 58
unit_exposure['Microencapsulated']['Gardens / Trees']['Hose-end Sprayer']['ft2']['dermal'] = 58
unit_exposure['Microencapsulated']['Lawns / Turf']['Hose-end Sprayer']['']['dermal'] = 13.4
unit_exposure['Microencapsulated']['Lawns / Turf']['Manually-pressurized handwand']['']['dermal'] = 63
unit_exposure['Microencapsulated']['Gardens / Trees']['Backpack']['gallons']['dermal'] = 130
unit_exposure['Microencapsulated']['Gardens / Trees']['Backpack']['ft2']['dermal'] = 130
unit_exposure['Microencapsulated']['Lawns / Turf']['Backpack']['']['dermal'] = 130
unit_exposure['Microencapsulated']['Gardens / Trees']['Sprinkler can']['gallons']['dermal'] = 58
unit_exposure['Microencapsulated']['Gardens / Trees']['Sprinkler can']['ft2']['dermal'] = 58
unit_exposure['Microencapsulated']['Lawns / Turf']['Sprinkler can']['']['dermal'] = 13.4
unit_exposure['Ready-to-use']['Paints / Preservatives']['Aerosol can']['']['dermal'] = 370
unit_exposure['Paints / Preservatives/ Stains']['Paints / Preservatives']['Airless Sprayer']['']['dermal'] = 160
unit_exposure['Paints / Preservatives/ Stains']['Paints / Preservatives']['Brush']['']['dermal'] = 450
unit_exposure['Paints / Preservatives/ Stains']['Paints / Preservatives']['Manually-pressurized handwand']['']['dermal'] = 63
unit_exposure['Paints / Preservatives/ Stains']['Paints / Preservatives']['Roller']['']['dermal'] = 450
unit_exposure['Liquid concentrate']['Treated Pets']['Dip']['']['dermal'] = 100
unit_exposure['Liquid concentrate']['Treated Pets']['Sponge']['']['dermal'] = 1600
unit_exposure['Ready-to-use']['Treated Pets']['Trigger-spray bottle']['']['dermal'] = 820
unit_exposure['Ready-to-use']['Treated Pets']['Aerosol can']['']['dermal'] = 820
unit_exposure['Ready-to-use']['Treated Pets']['Shampoo']['']['dermal'] = 2000
unit_exposure['Ready-to-use']['Treated Pets']['Spot-on']['']['dermal'] = 120
unit_exposure['Ready-to-use']['Treated Pets']['Collar']['']['dermal'] = 120
unit_exposure['Dust/Powder']['Treated Pets']['Shaker Can']['']['dermal'] = 4300


unit_exposure['Dust/Powder']['Indoor Environment']['Plunger Duster']['Broadcast; Perimeter/Spot/ Bedbug (course application)']['inhalation'] = 1.7
unit_exposure['Dust/Powder']['Gardens / Trees']['Plunger Duster']['']['inhalation'] = 1.7
unit_exposure['Dust/Powder']['Indoor Environment']['Bulb duster']['Perimeter/Spot/Bedbug; Crack and Crevice']['inhalation'] = 1.7
unit_exposure['Dust/Powder']['Gardens / Trees']['Bulb duster']['']['inhalation'] = 1.7
unit_exposure['Dust/Powder']['Indoor Environment']['Electric/power duster']['Broadcast; Perimeter/Spot/ Bedbug (course application)']['inhalation'] = 18
unit_exposure['Dust/Powder']['Gardens / Trees']['Electric/power duster']['']['inhalation'] = 18
unit_exposure['Dust/Powder']['Indoor Environment']['Hand crank duster']['Broadcast; Perimeter/Spot/ Bedbug (course application)']['inhalation'] = 18
unit_exposure['Dust/Powder']['Gardens / Trees']['Hand crank duster']['']['inhalation'] = 18
unit_exposure['Dust/Powder']['Indoor Environment']['Shaker can']['Broadcast']['inhalation'] = 18
unit_exposure['Dust/Powder']['Indoor Environment']['Shaker can']['Broadcast; Perimeter/Spot/ Bedbug (course application)']['inhalation'] = 18
unit_exposure['Dust/Powder']['Gardens / Trees']['Shaker can']['can']['inhalation'] = 18
unit_exposure['Dust/Powder']['Gardens / Trees']['Shaker can']['ft2']['inhalation'] = 18
unit_exposure['Liquid concentrate']['Indoor Environment']['Manually-pressurized handwand (w/ or w/o pin stream nozzle)']['Broadcast, Perimeter/Spot/ Bedbug (course application); Perimeter /Spot/ Bedbug (pinstream application); Crack and Crevice']['inhalation'] = 1.1
unit_exposure['Liquid concentrate']['Gardens / Trees']['Manually-pressurized handwand']['gallons']['inhalation'] = 0.018
unit_exposure['Liquid concentrate']['Gardens / Trees']['Manually-pressurized handwand']['ft2']['inhalation'] = 0.018
unit_exposure['Liquid concentrate']['Gardens / Trees']['Hose-end Sprayer']['ft2']['inhalation'] = 0.0014
unit_exposure['Liquid concentrate']['Gardens / Trees']['Hose-end Sprayer']['gallons']['inhalation'] = 0.0014
unit_exposure['Liquid concentrate']['Lawns / Turf']['Hose-end Sprayer']['']['inhalation'] = 0.022
unit_exposure['Liquid concentrate']['Lawns / Turf']['Manually-pressurized handwand']['']['inhalation'] = 0.018
unit_exposure['Liquid concentrate']['Gardens / Trees']['Backpack']['gallons']['inhalation'] = 0.14
unit_exposure['Liquid concentrate']['Gardens / Trees']['Backpack']['ft2']['inhalation'] = 0.14
unit_exposure['Liquid concentrate']['Gardens / Trees']['Sprinkler can']['gallons']['inhalation'] = 0.0014
unit_exposure['Liquid concentrate']['Gardens / Trees']['Sprinkler can']['ft2']['inhalation'] = 0.0014
unit_exposure['Liquid concentrate']['Lawns / Turf']['Sprinkler can']['']['inhalation'] = 0.022
unit_exposure['Ready-to-use']['Indoor Environment']['Aerosol can']['Broadcast Surface Spray']['inhalation'] = 3
unit_exposure['Ready-to-use']['Indoor Environment']['Aerosol can']['Perimeter/ Spot/ Bedbug (course application)']['inhalation'] = 3
unit_exposure['Ready-to-use']['Indoor Environment']['Aerosol can with pin stream nozzle']['Perimeter/ Spot/ Bedbug (pin stream application); Crack and Crevice']['inhalation'] = 3
unit_exposure['Ready-to-use']['Indoor Environment']['Aerosol can']['Space spray']['inhalation'] = 3
unit_exposure['Ready-to-use']['Gardens / Trees']['Aerosol can']['']['inhalation'] = 3
unit_exposure['Ready-to-use']['Lawns / Turf']['Aerosol can']['']['inhalation'] = 3
unit_exposure['Ready-to-use']['Indoor Environment']['Trigger-spray bottle']['Broadcast']['inhalation'] = 0.061
unit_exposure['Ready-to-use']['Indoor Environment']['Trigger-spray bottle']['Perimeter/ Spot/ Bedbug (course application)']['inhalation'] = 0.061
unit_exposure['Ready-to-use']['Gardens / Trees']['Trigger-spray bottle']['']['inhalation'] = 0.061
unit_exposure['Ready-to-use']['Lawns / Turf']['Trigger-spray bottle']['']['inhalation'] = 0.061
unit_exposure['Ready-to-use']['Indoor Environment']['Gels']['No exposure data available for this application scenario; however, exposure is considered negligible.']['inhalation'] = 0
unit_exposure['Ready-to-use']['Indoor Environment']['Pastes']['No exposure data available for this application scenario; however, exposure is considered negligible.']['inhalation'] = 0
unit_exposure['Ready-to-use']['Indoor Environment']['Foams']['No exposure data available for this application scenario; however, exposure is considered negligible.']['inhalation'] = 0
unit_exposure['Ready-to-use']['Indoor Environment']['Bait (granular, hand dispersal)']['']['inhalation'] = 0.38
unit_exposure['Ready-to-use']['Indoor Environment']['Bait station / trap (enclosed in child resistant packaging)']['No exposure data available for this application scenario; however, exposure is considered negligible.']['inhalation'] = 0
unit_exposure['Ready-to-use']['Indoor Environment']['Pest strip']['No exposure data available for this application scenario; however, exposure is considered negligible.']['inhalation'] = 0
unit_exposure['Ready-to-use']['Gardens / Trees']['Hose-end Sprayer']['gallons']['inhalation'] = 0.034
unit_exposure['Ready-to-use']['Gardens / Trees']['Hose-end Sprayer']['ft2']['inhalation'] = 0.034
unit_exposure['Ready-to-use']['Lawns / Turf']['Hose-end Sprayer']['']['inhalation'] = 0.034
unit_exposure['Wettable powders']['Indoor Environment']['Manually-pressurized handwand (w/ or w/o pin stream nozzle)']['Broadcast, Perimeter/Spot/ Bedbug (course application); Perimeter /Spot/ Bedbug (pinstream application); Crack and Crevice']['inhalation'] = 1.1
unit_exposure['Liquid concentrate']['Lawns / Turf']['Backpack']['']['inhalation'] = 0.14
unit_exposure['Wettable powders']['Gardens / Trees']['Manually-pressurized handwand']['gallons']['inhalation'] = 1.1
unit_exposure['Wettable powders']['Gardens / Trees']['Manually-pressurized handwand']['ft2']['inhalation'] = 1.1
unit_exposure['Wettable powders']['Gardens / Trees']['Hose-end Sprayer']['gallons']['inhalation'] = 0.0014
unit_exposure['Wettable powders']['Gardens / Trees']['Hose-end Sprayer']['ft2']['inhalation'] = 0.0014
unit_exposure['Wettable powders']['Lawns / Turf']['Hose-end Sprayer']['']['inhalation'] = 0.022
unit_exposure['Wettable powders']['Lawns / Turf']['Manually-pressurized handwand']['']['inhalation'] = 1.1
unit_exposure['Wettable powders']['Gardens / Trees']['Backpack']['gallons']['inhalation'] = 1.1
unit_exposure['Wettable powders']['Gardens / Trees']['Backpack']['ft2']['inhalation'] = 1.1
unit_exposure['Wettable powders']['Gardens / Trees']['Sprinkler can']['gallons']['inhalation'] = 0.0014
unit_exposure['Wettable powders']['Gardens / Trees']['Sprinkler can']['ft2']['inhalation'] = 0.0014
unit_exposure['Wettable powders']['Lawns / Turf']['Sprinkler can']['']['inhalation'] = 0.022
unit_exposure['Wettable powders in water-soluble packaging']['Indoor Environment']['Manually-pressurized handwand (w/ or w/o pin stream nozzle)']['Broadcast, Perimeter/Spot/ Bedbug (course application); Perimeter /Spot/ Bedbug (pinstream application); Crack and Crevice']['inhalation'] = 1.1
unit_exposure['Wettable powders']['Lawns / Turf']['Backpack']['']['inhalation'] = 1.1
unit_exposure['Wettable powders in water-soluble packaging']['Gardens / Trees']['Manually-pressurized handwand']['gallons']['inhalation'] = 0.018
unit_exposure['Wettable powders in water-soluble packaging']['Gardens / Trees']['Manually-pressurized handwand']['ft2']['inhalation'] = 0.018
unit_exposure['Wettable powders in water-soluble packaging']['Gardens / Trees']['Hose-end Sprayer']['gallons']['inhalation'] = 0.034
unit_exposure['Wettable powders in water-soluble packaging']['Gardens / Trees']['Hose-end Sprayer']['ft2']['inhalation'] = 0.034
unit_exposure['Wettable powders in water-soluble packaging']['Lawns / Turf']['Hose-end Sprayer']['']['inhalation'] = 0.034
unit_exposure['Wettable powders in water-soluble packaging']['Lawns / Turf']['Manually-pressurized handwand']['']['inhalation'] = 0.018
unit_exposure['Wettable powders in water-soluble packaging']['Lawns / Turf']['Backpack']['']['inhalation'] = 0.018
unit_exposure['Wettable powders in water-soluble packaging']['Gardens / Trees']['Sprinkler can']['gallons']['inhalation'] = 0.034
unit_exposure['Wettable powders in water-soluble packaging']['Gardens / Trees']['Sprinkler can']['ft2']['inhalation'] = 0.034
unit_exposure['Wettable powders in water-soluble packaging']['Lawns / Turf']['Sprinkler can']['']['inhalation'] = 0.034
unit_exposure['Wettable powders in water-soluble packaging']['Gardens / Trees']['Backpack']['']['inhalation'] = 0.018
unit_exposure['Water-disersible Granule / Dry Flowable']['Lawns / Turf']['Manually-pressurized handwand']['']['inhalation'] = 1.1
unit_exposure['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Hose-end Sprayer']['gallons']['inhalation'] = 0.0014
unit_exposure['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Hose-end Sprayer']['ft2']['inhalation'] = 0.0014
unit_exposure['Water-disersible Granule / Dry Flowable']['Lawns / Turf']['Hose-end Sprayer']['']['inhalation'] = 0.022
unit_exposure['Wettable powders in water-soluble packaging']['Gardens / Trees']['Backpack']['']['inhalation'] = 0.018
unit_exposure['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Manually-pressurized handwand']['gallons']['inhalation'] = 1.1
unit_exposure['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Manually-pressurized handwand']['ft2']['inhalation'] = 1.1
unit_exposure['Water-disersible Granule / Dry Flowable']['Lawns / Turf']['Backpack']['']['inhalation'] = 1.1
unit_exposure['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Sprinkler can']['gallons']['inhalation'] = 0.0014
unit_exposure['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Sprinkler can']['ft2']['inhalation'] = 0.0014
unit_exposure['Water-disersible Granule / Dry Flowable']['Lawns / Turf']['Sprinkler can']['']['inhalation'] = 0.022
unit_exposure['Granule']['Gardens / Trees']['Push-type rotary spreader']['']['inhalation'] = 0.0026
unit_exposure['Granule']['Lawns / Turf']['Push-type rotary spreader']['']['inhalation'] = 0.0026
unit_exposure['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Backpack']['gallons']['inhalation'] = 1.1
unit_exposure['Water-disersible Granule / Dry Flowable']['Gardens / Trees']['Backpack']['ft2']['inhalation'] = 1.1
unit_exposure['Granule']['Lawns / Turf']['Belly grinder']['']['inhalation'] = 0.039
unit_exposure['Granule']['Gardens / Trees']['Spoon']['']['inhalation'] = 0.087
unit_exposure['Granule']['Lawns / Turf']['Spoon']['']['inhalation'] = 0.087
unit_exposure['Granule']['Gardens / Trees']['Cup']['']['inhalation'] = 0.013
unit_exposure['Granule']['Lawns / Turf']['Cup']['']['inhalation'] = 0.013
unit_exposure['Granule']['Gardens / Trees']['Hand dispersal']['']['inhalation'] = 0.38
unit_exposure['Granule']['Lawns / Turf']['Hand dispersal']['']['inhalation'] = 0.38
unit_exposure['Granule']['Gardens / Trees']['Shaker can']['can']['inhalation'] = 0.013
unit_exposure['Granule']['Gardens / Trees']['Shaker can']['ft2']['inhalation'] = 0.013
unit_exposure['Granule']['Lawns / Turf']['Shaker can']['']['inhalation'] = 0.013
unit_exposure['Microencapsulated']['Gardens / Trees']['Manually-pressurized handwand']['gallons']['inhalation'] = 0.018
unit_exposure['Microencapsulated']['Gardens / Trees']['Manually-pressurized handwand']['ft2']['inhalation'] = 0.018
unit_exposure['Microencapsulated']['Gardens / Trees']['Hose-end Sprayer']['gallons']['inhalation'] = 0.0014
unit_exposure['Microencapsulated']['Gardens / Trees']['Hose-end Sprayer']['ft2']['inhalation'] = 0.0014
unit_exposure['Microencapsulated']['Lawns / Turf']['Hose-end Sprayer']['']['inhalation'] = 0.022
unit_exposure['Microencapsulated']['Lawns / Turf']['Manually-pressurized handwand']['']['inhalation'] = 0.018
unit_exposure['Microencapsulated']['Gardens / Trees']['Backpack']['gallons']['inhalation'] = 0.14
unit_exposure['Microencapsulated']['Gardens / Trees']['Backpack']['ft2']['inhalation'] = 0.14
unit_exposure['Microencapsulated']['Lawns / Turf']['Backpack']['']['inhalation'] = 0.14
unit_exposure['Microencapsulated']['Gardens / Trees']['Sprinkler can']['gallons']['inhalation'] = 0.0014
unit_exposure['Microencapsulated']['Gardens / Trees']['Sprinkler can']['ft2']['inhalation'] = 0.0014
unit_exposure['Microencapsulated']['Lawns / Turf']['Sprinkler can']['']['inhalation'] = 0.022
unit_exposure['Ready-to-use']['Paints / Preservatives']['Aerosol can']['']['inhalation'] = 3
unit_exposure['Paints / Preservatives/ Stains']['Paints / Preservatives']['Airless Sprayer']['']['inhalation'] = 0.56
unit_exposure['Paints / Preservatives/ Stains']['Paints / Preservatives']['Brush']['']['inhalation'] = 0.2
unit_exposure['Paints / Preservatives/ Stains']['Paints / Preservatives']['Manually-pressurized handwand']['']['inhalation'] = 0.018
unit_exposure['Paints / Preservatives/ Stains']['Paints / Preservatives']['Roller']['']['inhalation'] = 0.2
unit_exposure['Liquid concentrate']['Treated Pets']['Dip']['']['inhalation'] = 0.027
unit_exposure['Liquid concentrate']['Treated Pets']['Sponge']['']['inhalation'] = 0.21
unit_exposure['Ready-to-use']['Treated Pets']['Trigger-spray bottle']['']['inhalation'] = 3.3
unit_exposure['Ready-to-use']['Treated Pets']['Aerosol can']['']['inhalation'] = 3.3
unit_exposure['Ready-to-use']['Treated Pets']['Shampoo']['']['inhalation'] = 0.29
unit_exposure['Ready-to-use']['Treated Pets']['Spot-on']['Negligible inhalation']['inhalation'] = 0#Negligible
unit_exposure['Ready-to-use']['Treated Pets']['Collar']['Negligible inhalation']['inhalation'] = 0#Negligible
unit_exposure['Dust/Powder']['Treated Pets']['Shaker Can']['']['inhalation'] = 18



daily_usage['Ready-to-use']['Insect Repellent']['Aerosol can'][''] = 1
daily_usage['Ready-to-use']['Insect Repellent']['Trigger-spray bottle'][''] = 1

unit_exposure['Ready-to-use']['Insect Repellent']['Aerosol can']['']['inhalation'] = 3
unit_exposure['Ready-to-use']['Insect Repellent']['Trigger-spray bottle']['']['inhalation'] = 0.061


#



from exposure_profile import ExposureProfile

def general_handler_sop(POD, LOC, bodyweight, absorption, application_rate):
    exposure_profile = ExposureProfile(bodyweight, POD, LOC, dermal_absorption=absorption['dermal'], inhalation_absorption=absorption['inhalation'])

    for formulation in unit_exposure: #application_rate[formulation][scenario][application_method][application_type]
        for scenario in unit_exposure[formulation]:
            for application_method in unit_exposure[formulation][scenario]:
                for application_type in unit_exposure[formulation][scenario][application_method]:
                    if application_type != "":
                        activity = "%s: %s (%s)" %(scenario, application_method, application_type)                
                    else:
                        activity = "%s: %s" %(scenario, application_method)                                        
                    for exposure_route in unit_exposure[formulation][scenario][application_method][application_type]:
                        if unit_exposure[formulation][scenario][application_method][application_type][exposure_route] > 0:
                            for lifestage in ['adult']:                                    
                                exposure = unit_exposure[formulation][scenario][application_method][application_type][exposure_route]
                                exposure *= application_rate[formulation][scenario][application_method][application_type] 
                                exposure *= daily_usage[formulation][scenario][application_method][application_type]
                                exposure_profile.update(exposure_route,formulation,activity,lifestage,exposure)


    #1_to_2 only for Insect Repellent # Inhalation only
    #Insect Repellent
    exposure_route = 'inhalation'
    formulation = 'Ready-to-use'
    scenario = 'Insect Repellent'
    application_type = ''
    for application_method in ['Aerosol can','Trigger-spray bottle']:
        if application_type != "":
            activity = "%s: %s (%s)" %(scenario, application_method, application_type)                
        else:
            activity = "%s: %s" %(scenario, application_method)  
        exposure = unit_exposure[formulation][scenario][application_method][application_type][exposure_route] 
        exposure *= application_rate[formulation][scenario][application_method][application_type] 
        exposure *= daily_usage[formulation][scenario][application_method][application_type]
        exposure_profile.update(exposure_route,formulation,activity,'1_to_2',exposure)                                                            


    return exposure_profile





